services:
  imoveis_database:
    image: postgres:17.2-alpine
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    depends_on:
      - imoveis_database
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8080:80"

  imoveis_api:
    image: imoveis_api
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - imoveis_database
    environment:
      DATABASE_URL: ${DATABASE_URL}

volumes:
  postgresdata: