services:
  imoveis_database:
    image: postgres:17.2-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  imoveis_api:
    image: imoveis_api
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - imoveis_database
    environment:
      DATABASE_URL: ${DATABASE_URL}

volumes:
  pgdata: